### ISSUE TITLE
Move the backport bot and rename it. 

### ISSUE THREAD

**Issue by Carreau** [scientific-python/summit-2024#14]
- [ ] move the source code. 
 - [ ] move the app
 - [ ] give access to heroku. 
 - [ ] update website with metrics. 
 - [ ] give access the the mail/bot-account. 
 - [ ] Make a new logo/page/name.
 - [ ] Access to keen.io ?
 - [ ] Make sure Steve Silvester still have access to everything.

**Comment by bsipocz** [comment]
I would transfer and reopen this issue to this year's repo. The previously blocking access right issue should be fixed now and I'm very determined to help with this task.
